name: Generate Python Tests
description: 為當前 Python 檔案生成 Pytest 單元測試並執行
trigger: /test

steps:
  - name: 分析程式碼
    instruction: |
      閱讀當前開啟的 Python 檔案。
      理解其商業邏輯、輸入與輸出型別。

  - name: 撰寫測試
    instruction: |
      在 `tests/` 資料夾下建立對應的 `test_<filename>.py`。
      使用 `pytest` 框架。
      包含正常情況 (Happy Path) 與邊緣情況 (Edge Cases)。
      請確保測試程式碼中有繁體中文註解。

  - name: 執行與修正
    instruction: |
      執行 `pytest`。
      如果測試失敗，請分析錯誤原因，並嘗試自動修復原始程式碼或測試程式碼。
      重複此步驟直到測試通過或嘗試 3 次為止。