name: Senior Python Code Review
description: 進行嚴格的代碼審查並提供繁體中文報告
trigger: /review_python

steps:
  - name: 安全與效能檢查
    instruction: |
      掃描程式碼中的潛在資安漏洞（如 SQL Injection, 硬編碼金鑰）。
      檢查時間複雜度，指出可能的效能瓶頸。

  - name: 風格檢查
    instruction: |
      檢查是否符合 PEP 8 (Python) 規範。
      檢查變數命名是否語意清晰。

  - name: 產出報告
    instruction: |
      總結上述發現。
      輸出格式如下：
      ### 🔍 代碼審查報告
      - **評分**：(1-10分)
      - **主要問題**：(列點)
      - **優化建議**：(提供修改後的代碼範例)
      
      請全程使用繁體中文，語氣需專業且友善。